use_frameworks!
platform :ios, '11.0'

target :CollectionViewCenteredFlowLayout do
  pod 'CollectionViewCenteredFlowLayout', :path => '..'
  
  # best practices
  pod 'SwiftLint', '~> 0'
  
  target 'CollectionViewCenteredFlowLayoutTests' do
      inherit! :search_paths
  end
end
